# This file is part of the Biopython distribution and governed by your
# choice of the "Biopython License Agreement" or the "BSD 3-Clause License".
# Please see the LICENSE file that should have been included as part of this
# package.
"""Type stubs for the C extension Bio.Align._alignmentcounts."""

from typing import Any
from typing import TypeAlias

from _typeshed import ReadableBuffer
from _typeshed import WriteableBuffer
from numpy.typing import NDArray

from Bio.Align._pairwisealigner import PairwiseAligner

# numpy's stubs give ndarray __buffer__ only on Python 3.12+.
_Buffer: TypeAlias = ReadableBuffer | NDArray[Any]
_WriteableBuffer: TypeAlias = WriteableBuffer | NDArray[Any]

class AlignmentCounts:
    # Each item of sequences is a buffer of letters or of int32 indices, any
    # other sequence of letters, or None. coordinates is a 2D intp array and
    # strands a 1D bool array. The optional argument is an aligner, a
    # wildcard character, or a substitution matrix. A subclass still gets an
    # AlignmentCounts.
    def __new__(
        cls,
        sequences: list[Any],
        coordinates: _WriteableBuffer,
        strands: _Buffer,
        argument: PairwiseAligner | str | _Buffer = ...,
    ) -> AlignmentCounts: ...
    # None if unknown.
    @property
    def score(self) -> float | None: ...
    @property
    def substitution_score(self) -> float | None: ...
    @property
    def gap_score(self) -> float | None: ...
    # None without a substitution matrix.
    @property
    def positives(self) -> int | None: ...
    @property
    def aligned(self) -> int: ...
    @property
    def identities(self) -> int: ...
    @property
    def mismatches(self) -> int: ...
    @property
    def gaps(self) -> int: ...
    @property
    def open_gaps(self) -> int: ...
    @property
    def extend_gaps(self) -> int: ...
    @property
    def open_left_gaps(self) -> int: ...
    @property
    def open_right_gaps(self) -> int: ...
    @property
    def open_internal_gaps(self) -> int: ...
    @property
    def extend_left_gaps(self) -> int: ...
    @property
    def extend_right_gaps(self) -> int: ...
    @property
    def extend_internal_gaps(self) -> int: ...
    @property
    def open_left_insertions(self) -> int: ...
    @property
    def open_left_deletions(self) -> int: ...
    @property
    def open_right_insertions(self) -> int: ...
    @property
    def open_right_deletions(self) -> int: ...
    @property
    def open_internal_insertions(self) -> int: ...
    @property
    def open_internal_deletions(self) -> int: ...
    @property
    def extend_left_insertions(self) -> int: ...
    @property
    def extend_left_deletions(self) -> int: ...
    @property
    def extend_right_insertions(self) -> int: ...
    @property
    def extend_right_deletions(self) -> int: ...
    @property
    def extend_internal_insertions(self) -> int: ...
    @property
    def extend_internal_deletions(self) -> int: ...
    @property
    def left_insertions(self) -> int: ...
    @property
    def left_deletions(self) -> int: ...
    @property
    def right_insertions(self) -> int: ...
    @property
    def right_deletions(self) -> int: ...
    @property
    def internal_insertions(self) -> int: ...
    @property
    def internal_deletions(self) -> int: ...
    @property
    def insertions(self) -> int: ...
    @property
    def open_insertions(self) -> int: ...
    @property
    def extend_insertions(self) -> int: ...
    @property
    def deletions(self) -> int: ...
    @property
    def open_deletions(self) -> int: ...
    @property
    def extend_deletions(self) -> int: ...
    @property
    def left_gaps(self) -> int: ...
    @property
    def right_gaps(self) -> int: ...
    @property
    def internal_gaps(self) -> int: ...
