# This file is part of the Biopython distribution and governed by your
# choice of the "Biopython License Agreement" or the "BSD 3-Clause License".
# Please see the LICENSE file that should have been included as part of this
# package.
"""Type stubs for the C extension Bio.Align._codonaligner."""

from typing import final
from typing import SupportsFloat
from typing import SupportsIndex
from typing import type_check_only
from typing import TypeAlias

from _typeshed import ReadableBuffer

# What the score setters accept: they convert with PyFloat_AsDouble.
_Score: TypeAlias = SupportsFloat | SupportsIndex

# The C module does not export this class; its tp_name is "Path generator".
# Each path is a (target, query) tuple of coordinates.
@final
@type_check_only
class PathGenerator:
    def __len__(self) -> int: ...
    def __iter__(self) -> PathGenerator: ...
    def __next__(self) -> tuple[tuple[int, ...], tuple[int, ...]]: ...
    def reset(self) -> None: ...

class CodonAligner:
    def __init__(self) -> None: ...
    # sA is the protein; sB0, sB1 and sB2 are the nucleotide sequence
    # translated in each of the three frames.
    def score(
        self,
        sA: ReadableBuffer,
        sB0: ReadableBuffer,
        sB1: ReadableBuffer,
        sB2: ReadableBuffer,
    ) -> float: ...
    def align(
        self,
        sA: ReadableBuffer,
        sB0: ReadableBuffer,
        sB1: ReadableBuffer,
        sB2: ReadableBuffer,
    ) -> tuple[float, PathGenerator]: ...
    @property
    def match_score(self) -> float: ...
    @match_score.setter
    def match_score(self, value: _Score) -> None: ...
    @property
    def mismatch_score(self) -> float: ...
    @mismatch_score.setter
    def mismatch_score(self, value: _Score) -> None: ...
    @property
    def match(self) -> float: ...
    @match.setter
    def match(self, value: _Score) -> None: ...
    @property
    def mismatch(self) -> float: ...
    @mismatch.setter
    def mismatch(self, value: _Score) -> None: ...
    @property
    def epsilon(self) -> float: ...
    @epsilon.setter
    def epsilon(self, value: _Score) -> None: ...
    # A single ASCII character.
    @property
    def wildcard(self) -> str: ...
    @wildcard.setter
    def wildcard(self, value: str) -> None: ...
    @property
    def frameshift_minus_two_score(self) -> float: ...
    @frameshift_minus_two_score.setter
    def frameshift_minus_two_score(self, value: _Score) -> None: ...
    @property
    def frameshift_minus_one_score(self) -> float: ...
    @frameshift_minus_one_score.setter
    def frameshift_minus_one_score(self, value: _Score) -> None: ...
    @property
    def frameshift_plus_one_score(self) -> float: ...
    @frameshift_plus_one_score.setter
    def frameshift_plus_one_score(self, value: _Score) -> None: ...
    @property
    def frameshift_plus_two_score(self) -> float: ...
    @frameshift_plus_two_score.setter
    def frameshift_plus_two_score(self, value: _Score) -> None: ...
    @property
    def frameshift_minus_score(self) -> float: ...
    @frameshift_minus_score.setter
    def frameshift_minus_score(self, value: _Score) -> None: ...
    @property
    def frameshift_plus_score(self) -> float: ...
    @frameshift_plus_score.setter
    def frameshift_plus_score(self, value: _Score) -> None: ...
    @property
    def frameshift_one_score(self) -> float: ...
    @frameshift_one_score.setter
    def frameshift_one_score(self, value: _Score) -> None: ...
    @property
    def frameshift_two_score(self) -> float: ...
    @frameshift_two_score.setter
    def frameshift_two_score(self, value: _Score) -> None: ...
    @property
    def frameshift_score(self) -> float: ...
    @frameshift_score.setter
    def frameshift_score(self, value: _Score) -> None: ...
