# This file is part of the Biopython distribution and governed by your
# choice of the "Biopython License Agreement" or the "BSD 3-Clause License".
# Please see the LICENSE file that should have been included as part of this
# package.
"""Type stubs for the C extension Bio.Align._pairwisealigner."""

from collections.abc import Callable
from typing import Any
from typing import final
from typing import SupportsFloat
from typing import SupportsIndex
from typing import type_check_only
from typing import TypeAlias

from _typeshed import ReadableBuffer
from numpy.typing import NDArray

from Bio.Align.substitution_matrices import Array

# What the score setters accept: they convert with PyFloat_AsDouble.
_Score: TypeAlias = SupportsFloat | SupportsIndex
# A gap score function is called with the gap's position and length.
_GapFunction: TypeAlias = Callable[[int, int], float]
# numpy's stubs give ndarray __buffer__ only on Python 3.12+.
_Buffer: TypeAlias = ReadableBuffer | NDArray[Any]

# The C module does not export this class; its tp_name is "Path generator".
# Each path is a (target, query) tuple of coordinates.
@final
@type_check_only
class PathGenerator:
    def __len__(self) -> int: ...
    def __iter__(self) -> PathGenerator: ...
    def __next__(self) -> tuple[tuple[int, ...], tuple[int, ...]]: ...
    def reset(self) -> None: ...

class PairwiseAligner:
    def __init__(self) -> None: ...
    def score(self, sequenceA: _Buffer, sequenceB: _Buffer, strand: str) -> float: ...
    def align(
        self, sequenceA: _Buffer, sequenceB: _Buffer, strand: str
    ) -> tuple[float, PathGenerator]: ...
    @property
    def mode(self) -> str: ...
    @mode.setter
    def mode(self, value: str) -> None: ...
    # None while a substitution matrix is set.
    @property
    def match_score(self) -> float | None: ...
    @match_score.setter
    def match_score(self, value: _Score) -> None: ...
    @property
    def mismatch_score(self) -> float | None: ...
    @mismatch_score.setter
    def mismatch_score(self, value: _Score) -> None: ...
    @property
    def match(self) -> float | None: ...
    @match.setter
    def match(self, value: _Score) -> None: ...
    @property
    def mismatch(self) -> float | None: ...
    @mismatch.setter
    def mismatch(self, value: _Score) -> None: ...
    # The getter returns the object that was set: almost always an Array,
    # but any square matrix of doubles is accepted.
    @property
    def substitution_matrix(self) -> Array | Any | None: ...
    @substitution_matrix.setter
    def substitution_matrix(self, value: _Buffer | None) -> None: ...
    # Only these three take a gap score function.
    @property
    def gap_score(self) -> float | _GapFunction: ...
    @gap_score.setter
    def gap_score(self, value: _Score | _GapFunction) -> None: ...
    @property
    def open_gap_score(self) -> float: ...
    @open_gap_score.setter
    def open_gap_score(self, value: _Score) -> None: ...
    @property
    def extend_gap_score(self) -> float: ...
    @extend_gap_score.setter
    def extend_gap_score(self, value: _Score) -> None: ...
    @property
    def internal_gap_score(self) -> float: ...
    @internal_gap_score.setter
    def internal_gap_score(self, value: _Score) -> None: ...
    @property
    def open_internal_gap_score(self) -> float: ...
    @open_internal_gap_score.setter
    def open_internal_gap_score(self, value: _Score) -> None: ...
    @property
    def extend_internal_gap_score(self) -> float: ...
    @extend_internal_gap_score.setter
    def extend_internal_gap_score(self, value: _Score) -> None: ...
    @property
    def end_gap_score(self) -> float: ...
    @end_gap_score.setter
    def end_gap_score(self, value: _Score) -> None: ...
    @property
    def open_end_gap_score(self) -> float: ...
    @open_end_gap_score.setter
    def open_end_gap_score(self, value: _Score) -> None: ...
    @property
    def extend_end_gap_score(self) -> float: ...
    @extend_end_gap_score.setter
    def extend_end_gap_score(self, value: _Score) -> None: ...
    @property
    def left_gap_score(self) -> float: ...
    @left_gap_score.setter
    def left_gap_score(self, value: _Score) -> None: ...
    @property
    def open_left_gap_score(self) -> float: ...
    @open_left_gap_score.setter
    def open_left_gap_score(self, value: _Score) -> None: ...
    @property
    def extend_left_gap_score(self) -> float: ...
    @extend_left_gap_score.setter
    def extend_left_gap_score(self, value: _Score) -> None: ...
    @property
    def right_gap_score(self) -> float: ...
    @right_gap_score.setter
    def right_gap_score(self, value: _Score) -> None: ...
    @property
    def open_right_gap_score(self) -> float: ...
    @open_right_gap_score.setter
    def open_right_gap_score(self, value: _Score) -> None: ...
    @property
    def extend_right_gap_score(self) -> float: ...
    @extend_right_gap_score.setter
    def extend_right_gap_score(self, value: _Score) -> None: ...
    @property
    def open_insertion_score(self) -> float: ...
    @open_insertion_score.setter
    def open_insertion_score(self, value: _Score) -> None: ...
    @property
    def extend_insertion_score(self) -> float: ...
    @extend_insertion_score.setter
    def extend_insertion_score(self, value: _Score) -> None: ...
    @property
    def insertion_score(self) -> float | _GapFunction: ...
    @insertion_score.setter
    def insertion_score(self, value: _Score | _GapFunction) -> None: ...
    @property
    def open_deletion_score(self) -> float: ...
    @open_deletion_score.setter
    def open_deletion_score(self, value: _Score) -> None: ...
    @property
    def extend_deletion_score(self) -> float: ...
    @extend_deletion_score.setter
    def extend_deletion_score(self, value: _Score) -> None: ...
    @property
    def deletion_score(self) -> float | _GapFunction: ...
    @deletion_score.setter
    def deletion_score(self, value: _Score | _GapFunction) -> None: ...
    @property
    def end_insertion_score(self) -> float: ...
    @end_insertion_score.setter
    def end_insertion_score(self, value: _Score) -> None: ...
    @property
    def open_end_insertion_score(self) -> float: ...
    @open_end_insertion_score.setter
    def open_end_insertion_score(self, value: _Score) -> None: ...
    @property
    def extend_end_insertion_score(self) -> float: ...
    @extend_end_insertion_score.setter
    def extend_end_insertion_score(self, value: _Score) -> None: ...
    @property
    def open_internal_insertion_score(self) -> float: ...
    @open_internal_insertion_score.setter
    def open_internal_insertion_score(self, value: _Score) -> None: ...
    @property
    def extend_internal_insertion_score(self) -> float: ...
    @extend_internal_insertion_score.setter
    def extend_internal_insertion_score(self, value: _Score) -> None: ...
    @property
    def internal_insertion_score(self) -> float: ...
    @internal_insertion_score.setter
    def internal_insertion_score(self, value: _Score) -> None: ...
    @property
    def open_left_insertion_score(self) -> float: ...
    @open_left_insertion_score.setter
    def open_left_insertion_score(self, value: _Score) -> None: ...
    @property
    def extend_left_insertion_score(self) -> float: ...
    @extend_left_insertion_score.setter
    def extend_left_insertion_score(self, value: _Score) -> None: ...
    @property
    def left_insertion_score(self) -> float: ...
    @left_insertion_score.setter
    def left_insertion_score(self, value: _Score) -> None: ...
    @property
    def open_right_insertion_score(self) -> float: ...
    @open_right_insertion_score.setter
    def open_right_insertion_score(self, value: _Score) -> None: ...
    @property
    def extend_right_insertion_score(self) -> float: ...
    @extend_right_insertion_score.setter
    def extend_right_insertion_score(self, value: _Score) -> None: ...
    @property
    def right_insertion_score(self) -> float: ...
    @right_insertion_score.setter
    def right_insertion_score(self, value: _Score) -> None: ...
    @property
    def end_deletion_score(self) -> float: ...
    @end_deletion_score.setter
    def end_deletion_score(self, value: _Score) -> None: ...
    @property
    def open_end_deletion_score(self) -> float: ...
    @open_end_deletion_score.setter
    def open_end_deletion_score(self, value: _Score) -> None: ...
    @property
    def extend_end_deletion_score(self) -> float: ...
    @extend_end_deletion_score.setter
    def extend_end_deletion_score(self, value: _Score) -> None: ...
    @property
    def open_internal_deletion_score(self) -> float: ...
    @open_internal_deletion_score.setter
    def open_internal_deletion_score(self, value: _Score) -> None: ...
    @property
    def extend_internal_deletion_score(self) -> float: ...
    @extend_internal_deletion_score.setter
    def extend_internal_deletion_score(self, value: _Score) -> None: ...
    @property
    def internal_deletion_score(self) -> float: ...
    @internal_deletion_score.setter
    def internal_deletion_score(self, value: _Score) -> None: ...
    @property
    def open_left_deletion_score(self) -> float: ...
    @open_left_deletion_score.setter
    def open_left_deletion_score(self, value: _Score) -> None: ...
    @property
    def extend_left_deletion_score(self) -> float: ...
    @extend_left_deletion_score.setter
    def extend_left_deletion_score(self, value: _Score) -> None: ...
    @property
    def left_deletion_score(self) -> float: ...
    @left_deletion_score.setter
    def left_deletion_score(self, value: _Score) -> None: ...
    @property
    def open_right_deletion_score(self) -> float: ...
    @open_right_deletion_score.setter
    def open_right_deletion_score(self, value: _Score) -> None: ...
    @property
    def extend_right_deletion_score(self) -> float: ...
    @extend_right_deletion_score.setter
    def extend_right_deletion_score(self, value: _Score) -> None: ...
    @property
    def right_deletion_score(self) -> float: ...
    @right_deletion_score.setter
    def right_deletion_score(self, value: _Score) -> None: ...
    @property
    def epsilon(self) -> float: ...
    @epsilon.setter
    def epsilon(self, value: _Score) -> None: ...
    # None, or a single character.
    @property
    def wildcard(self) -> str | None: ...
    @wildcard.setter
    def wildcard(self, value: str | None) -> None: ...
    @property
    def algorithm(self) -> str: ...
